apiVersion: apps/v1
kind: Deployment
metadata:
  name: mic-identity-depl
spec:
  selector:
    matchLabels:
      app: mic-identity
  template:
    metadata:
      labels:
        app: mic-identity
    spec:
      imagePullSecrets:
        - name: ghcr-auth
      containers:
        - image: ghcr.io/devpies/mic-identity:b1cba09
          name: mic-identity
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "250m"
              memory: "250Mi"
          env:
            - name: NATS_URL
              value: "nats://nats-svc:4222"
            - name: CLIENT_ID
              value: "mic-identity"
            - name: CLUSTER_ID
              value: "devpie-client"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: qa-mic-db-identity-database-name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: qa-mic-db-identity-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: qa-mic-db-identity-password
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: qa-mic-db-identity-host
      initContainers:
        - name: schema-migration
          image: devpies/mic-db-identity-migration:v000003
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: qa-mic-db-identity-url
          command: ["migrate"]
          args:
            ["-path", "/migrations", "-verbose", "-database", "$(DB_URL)", "up"]
