name: Deploy EKS Cluster

on:
  push:
    paths:
      - ".github/workflows/deploy-infra.yml"
      - "__infra__/**"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # terraform validate
      # terraform plan
      # terraform apply
