name: Deploy EKS Cluster

on:
  push:
    paths:
      - ".github/workflows/deploy-manifests.yml"
      - "manifests/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # ingress
      # ingress route
      # traefik
